log_level: INFO

elasticsearch:
  index_name: home-search-query-log
  key_field: query_log
  query_file: ../query/searchlog.json
  verify_certs: false

neo4j:
  # .env 값이 우선 적용되지만 기본값도 남겨둠
  uri: bolt://localhost:7687
  user: neo4j
  password: 2Engussla

user_pcid_export:
  gte: "2024-12-01T00:00:00.000"
  lte: "2025-01-01T00:00:00.000"
  size: 10000
  output_file: "./result/user_pcid_list.csv"

user_pcid_processing:
  pcid_list_file: "./result/user_pcid_list.csv"
  gte: "2024-12-01T00:00:00.000"
  lte: "2025-01-01T00:00:00.000"
  size: 10000
